### PR TITLE
Get it to build with clang on Ubuntu 14.04.

### PR DESCRIPTION
**Pull request by schneith**

### CODE REVIEW

**Comment by simonlynen** [comment]
@schneith I would prefer to keep openMP since I have that working on my mac with clang. Can you do a findpackage trick to circumvent this? I did sth similar in libnabo: https://github.com/ethz-asl/libnabo/blob/master/CMakeLists.txt#L52

**Comment by schneith** [comment]
Ok. Can I turn it off with if (CLANG && NOT APPLE)?

**Comment by simonlynen** [comment]
@schneith does the findpackage not work? Otherwise for now ok to do your suggestion. I can put up my short script to install openmp.

**Comment by schneith** [comment]
Ok got it to work, only the tests and examples have problems. Are you ok with disabling these?

**Pull request merged**
